### ISSUE TITLE
Can't connect to server using MacOS

### ISSUE THREAD

**Issue by EmanuelCastanho** [JuliaDatabases/MySQL.jl#192] opened 2022-09-07 14:04 UTC
I am using Julia on macOS Monterey to try to connect to a Digital Ocean Database, however I am getting this error:

```
conn = DBInterface.connect(MySQL.Connection, "HOST", "USER", "PASS", db = "DB", port = PORT)
ERROR: (2002): Can't connect to server on 'HOST' (60)
Stacktrace:
 [1] connect
   @ ~/.julia/packages/MySQL/3VbD5/src/api/capi.jl:12 [inlined]
 [2] MySQL.Connection(host::String, user::String, passwd::String, db::String, port::Int64, unix_socket::String; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ MySQL ~/.julia/packages/MySQL/3VbD5/src/MySQL.jl:34
 [3] Connection
   @ ~/.julia/packages/MySQL/3VbD5/src/MySQL.jl:24 [inlined]
 [4] #connect#5
   @ ~/.julia/packages/MySQL/3VbD5/src/MySQL.jl:288 [inlined]
 [5] top-level scope
   @ REPL[5]:1
```

Everything works fine when I try to connect using Ubuntu.

Do you know what could be the reason for this?

**Comment by jerlich** [comment] 2022-09-14 00:03
which version of Julia are you using? I found that 1.8 is giving errors but 1.7 works.

**Comment by essenciary** [comment] 2022-09-14 07:18
Confirmed. Yesterday I was struggling with the same problem, I thought it was on my side. 
Julia 1.8.1 - works when connecting locally (over socket) but fails to connect remotely (to a port).

**Comment by essenciary** [comment] 2022-09-14 07:37
Doesn't work on Julia 1.7.3 either.

**Comment by jerlich** [comment] 2022-09-14 08:25
This is my working config:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by essenciary** [comment] 2022-09-14 08:58
i can also confirm that it works correctly on Windows 11 (Julia 1.8.1)

**Comment by EmanuelCastanho** [comment] 2022-09-14 09:22
<img width="597" alt="Screenshot 2022-09-14 at 09 21 21" src="https://user-images.githubusercontent.com/69935277/190115419-1c70131b-61f2-4280-b4e2-a2c4107d8e82.png">

I can also provide my working config on my VM running Ubuntu.

**Comment by igaszczesniak** [comment] 2022-09-14 09:59
![image](https://user-images.githubusercontent.com/97889272/190123888-37e3a126-238e-49fb-bb6e-11ba7d0a9616.png)
 This version works correctly on Ubuntu but not on Mac

**Comment by igaszczesniak** [comment] 2022-09-14 12:04
Just checked Julia 1.7.1 on Mac and doesn't work for me.

**Comment by jerlich** [comment] 2022-09-14 13:57
@igaszczesniak can you provide your versioninfo and which packages you are using? My Julia 1.7.1 worked.

**Comment by jerlich** [comment] 2022-09-14 14:18
On my intel mac mini i can't connect at all (i tried 1.7.1, 1.7.3, 1.8.1) and i tried MySQL 1.3.1 and 1.2.1

**Comment by essenciary** [comment] 2022-09-14 14:59
@EmanuelCastanho No, I'm on M1.

**Comment by igaszczesniak** [comment] 2022-09-14 16:56
> @igaszczesniak can you provide your versioninfo and which packages you are using? My Julia 1.7.1 worked.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/97889272/190215158-0289d17e-1d1f-4121-bb16-1d2a03ce9b1f.png">
So in my case both versions 1.7.1 and 1.8.0 dont't work on Mac but 1.8.0 works on Ubuntu Linux. I am using MySQL and DBInterface just like above.

**Comment by AbhimanyuAryan** [comment] 2022-09-14 17:18
> 

not only on Intel based mac. Tested on 12.6 macbook m1 as mentioned in #193

**Comment by essenciary** [comment] 2022-09-21 10:02
Can we help on this one? Basically it looks like Julia no longer has MySQL support on macOS.

**Comment by quinnj** [comment] 2022-10-04 23:47
I'm using intel-based Julia 1.8 (via rosetta) on macos on an m1 machine and I'm seeing the same can't connect error. Looking into it.

**Comment by quinnj** [comment] 2022-10-05 04:25
Should be fixed by https://github.com/JuliaDatabases/MySQL.jl/pull/196; the answer for now is rolling back the MariaDB_Connector_C_jll version since things started failing when we bumped that version. Will tag a new release soon.

**Closed by quinnj** 2022-10-05 04:25 UTC

**Comment by jerlich** [comment] 2022-10-06 12:06
I can confirm that release 1.4.1 fixes the problem.
